### ISSUE TITLE
Error installing from pypi

### ISSUE THREAD

**Issue by chrisgorgo** [CognitiveAtlas/cogat-python#8]
```
Collecting cognitiveatlas
  Downloading cognitiveatlas-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-AgZxDy/cognitiveatlas/setup.py", line 4, in <module>
        reqs = [line.strip() for line in open('requirements.txt').readlines()]
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
```

To avoid this in the future I recommend doing 

```
pip install -e .
```

just before you run tests.

**Comment by vsoch** [comment]
Isn't the error because requirements.txt is not included with the egg?

**Comment by vsoch** [comment]
Ah I see, it writes them to:

```
  writing requirements to cognitiveatlas.egg-info/requires.txt
```

**Comment by vsoch** [comment]
Try now
